### ISSUE TITLE
Dividir o projeto em varios documentos

### ISSUE THREAD

**Issue by afonsopacifer** [PopUpDesign/Bookmarks#11]
O que você acha de dividir as seções do projeto em documentos,
por exemplo https://github.com/willianjusten/awesome-svg.

Como a tendência é só aumentar, acho que vai chegar em um ponto em que ficará muito trabalhoso rolar o scroll para navegar pelas categorias, além de meio confuso.

Se você achar uma boa, eu posso dividir e mandar um PR.  :D   

O que acha?

**Comment by daniguerrato** [comment]
Oi Afonso,
Acho uma ótima ideia! Você quer dividir ou prefere que eu faça isto?

Abraço!

**Comment by afonsopacifer** [comment]
Pode deixar que eu divido e mando para você avaliar,
eu estou no trampo agora, assim que chegar em casa eu divido e mando o PR. 
:D

**Comment by daniguerrato** [comment]
Ótimo! Obrigada! :D
