### ISSUE TITLE
Conteúdo relacionado a Front-End

### ISSUE THREAD

**Issue by afonsopacifer** [PopUpDesign/Bookmarks#2]
Vocês pretendem incluir mais conteúdo relacionados a Front-End?
Se sim eu posso ajudar :D 
imagino que como o foco é no Design, o ideal é focar em HTML/CSS, certo?
Eu vi um angularJS perdido ali, vocês pretendem abranger mais coisas sobre JS (no Front-End)?

**Comment by daniguerrato** [comment]
Oi Afonso!
Sim, a ideia é incluir mais coisas sobre Front-end! Se você tiver dicas boas sobre JS pode mandar bala! :D

**Comment by afonsopacifer** [comment]
Show! :+1:
