### ISSUE TITLE
Link de grupos estão quebrados

### ISSUE THREAD

**Issue by felippenardi** [PopUpDesign/Bookmarks#3]
Parece que todos os links para grupos no README estão quebrados. Não sei se é algo temporário do google mas, como o erro foi 404, eu acredito que não.

**Comment by daniguerrato** [comment]
Obrigada pela dica, Felippe!
Os endereços estavam corretos, mas faltava uma barra no final.

**Comment by felippenardi** [comment]
Ah sim :)
